//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;


namespace MVCAdminLteWithMySql.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class topic
    {
        public int TopicID { get; set; }

        [Required(ErrorMessage = "Title is required")]
        [StringLength(200)]
        public string Title { get; set; }
        [Required(ErrorMessage = "Description is required")]
        [StringLength(200)]
        [AllowHtml]
        public string Description { get; set; }
    }
}
