//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;


namespace MVCAdminLteWithMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserID { get; set; }

        [Required]
        [StringLength(200)]
        public string name { get; set; }
        [Required]
        [StringLength(200)]
        public string address { get; set; }
        [Required(ErrorMessage = "Tel number is necessary")]
        [Phone(ErrorMessage = "Tel number is not in correct format")]
        public string tel { get; set; }
        [Required(ErrorMessage = "email address iss necessary")]
        [EmailAddress(ErrorMessage = "Email address is not in a correct format")]
        public string email { get; set; }
    }
}
